//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bionly.Resx {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bionly.Resx.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System administrator ähnelt.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Air pressure ähnelt.
        /// </summary>
        internal static string AirPressure {
            get {
                return ResourceManager.GetString("AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Average values of the past ähnelt.
        /// </summary>
        internal static string AverageValues {
            get {
                return ResourceManager.GetString("AverageValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cancel ähnelt.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Change language ähnelt.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charts ähnelt.
        /// </summary>
        internal static string Charts {
            get {
                return ResourceManager.GetString("Charts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphs for &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string ChartsOf_Name {
            get {
                return ResourceManager.GetString("ChartsOf_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please restart the app to fully apply the language. ähnelt.
        /// </summary>
        internal static string CloseAppForLanguage {
            get {
                return ResourceManager.GetString("CloseAppForLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Close app now ähnelt.
        /// </summary>
        internal static string CloseNow {
            get {
                return ResourceManager.GetString("CloseNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connect ähnelt.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} of {1} devices connected ähnelt.
        /// </summary>
        internal static string ConnectedDevicesCountTxt {
            get {
                return ResourceManager.GetString("ConnectedDevicesCountTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection ähnelt.
        /// </summary>
        internal static string Connection {
            get {
                return ResourceManager.GetString("Connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Connection state: {0} ähnelt.
        /// </summary>
        internal static string ConnectionState {
            get {
                return ResourceManager.GetString("ConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Website School Biology Center Leipzig ähnelt.
        /// </summary>
        internal static string CustomerLinkTxt {
            get {
                return ResourceManager.GetString("CustomerLinkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dashboard ähnelt.
        /// </summary>
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete ähnelt.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string Delete_Name {
            get {
                return ResourceManager.GetString("Delete_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Not all content related to this device could be removed. ähnelt.
        /// </summary>
        internal static string DeleteDeviceContentsFailed {
            get {
                return ResourceManager.GetString("DeleteDeviceContentsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Delete failed ähnelt.
        /// </summary>
        internal static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dependencies ähnelt.
        /// </summary>
        internal static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Description ähnelt.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Developer ähnelt.
        /// </summary>
        internal static string Developer {
            get {
                return ResourceManager.GetString("Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Developer on GitHub ähnelt.
        /// </summary>
        internal static string DeveloperLinkTxt {
            get {
                return ResourceManager.GetString("DeveloperLinkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die This device was not found. ähnelt.
        /// </summary>
        internal static string DeviceNotFound {
            get {
                return ResourceManager.GetString("DeviceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Devices ähnelt.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Device with contents ähnelt.
        /// </summary>
        internal static string DeviceWithContents {
            get {
                return ResourceManager.GetString("DeviceWithContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Edit device ähnelt.
        /// </summary>
        internal static string EditDevice {
            get {
                return ResourceManager.GetString("EditDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die End video ähnelt.
        /// </summary>
        internal static string EndVideo {
            get {
                return ResourceManager.GetString("EndVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error during fetching ähnelt.
        /// </summary>
        internal static string ErrorOnCall {
            get {
                return ResourceManager.GetString("ErrorOnCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The list of images could not be fetched! ähnelt.
        /// </summary>
        internal static string ErrorOnImageLoading {
            get {
                return ResourceManager.GetString("ErrorOnImageLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loading users not possible ähnelt.
        /// </summary>
        internal static string ErrorOnUserLoad {
            get {
                return ResourceManager.GetString("ErrorOnUserLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The user cannot be saved. ähnelt.
        /// </summary>
        internal static string ErrorOnUserSave {
            get {
                return ResourceManager.GetString("ErrorOnUserSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FTP port ähnelt.
        /// </summary>
        internal static string FtpPort {
            get {
                return ResourceManager.GetString("FtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Good day ähnelt.
        /// </summary>
        internal static string GoodDay {
            get {
                return ResourceManager.GetString("GoodDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Good evening ähnelt.
        /// </summary>
        internal static string GoodEvening {
            get {
                return ResourceManager.GetString("GoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Good morning ähnelt.
        /// </summary>
        internal static string GoodMorning {
            get {
                return ResourceManager.GetString("GoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Humidity ähnelt.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ID ähnelt.
        /// </summary>
        internal static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username or password not correct ähnelt.
        /// </summary>
        internal static string IncorrectUserCredits {
            get {
                return ResourceManager.GetString("IncorrectUserCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP address ähnelt.
        /// </summary>
        internal static string IpAdress {
            get {
                return ResourceManager.GetString("IpAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die IP adress / Domain ähnelt.
        /// </summary>
        internal static string IpAdressDomain {
            get {
                return ResourceManager.GetString("IpAdressDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Liveview ähnelt.
        /// </summary>
        internal static string Liveview {
            get {
                return ResourceManager.GetString("Liveview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Login ähnelt.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Continue as guest ähnelt.
        /// </summary>
        internal static string LoginAsGuest {
            get {
                return ResourceManager.GetString("LoginAsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Logout ähnelt.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manage ähnelt.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurements from {0} ähnelt.
        /// </summary>
        internal static string MeasurementsOf_Name {
            get {
                return ResourceManager.GetString("MeasurementsOf_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Measurments ähnelt.
        /// </summary>
        internal static string Measurments {
            get {
                return ResourceManager.GetString("Measurments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New device ähnelt.
        /// </summary>
        internal static string NewDevice {
            get {
                return ResourceManager.GetString("NewDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New language could not be saved ähnelt.
        /// </summary>
        internal static string NewLangError {
            get {
                return ResourceManager.GetString("NewLangError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New password ähnelt.
        /// </summary>
        internal static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die New password does not match ähnelt.
        /// </summary>
        internal static string NewPasswordNoMatch {
            get {
                return ResourceManager.GetString("NewPasswordNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new password for user {0} has been saved! ähnelt.
        /// </summary>
        internal static string NewPasswordSavedFor_Name {
            get {
                return ResourceManager.GetString("NewPasswordSavedFor_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The new username is now &quot;{0}&quot;. ähnelt.
        /// </summary>
        internal static string NewUserIs_Name {
            get {
                return ResourceManager.GetString("NewUserIs_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No device selected for measurements ähnelt.
        /// </summary>
        internal static string NoDeviceForMeasurements {
            get {
                return ResourceManager.GetString("NoDeviceForMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No devices configured ähnelt.
        /// </summary>
        internal static string NoDevicesConfigured {
            get {
                return ResourceManager.GetString("NoDevicesConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The live view is unfortunately not available under Windows ähnelt.
        /// </summary>
        internal static string NoLiveviewWin {
            get {
                return ResourceManager.GetString("NoLiveviewWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app does not have the required permissions to delete this device. ähnelt.
        /// </summary>
        internal static string NoPermissionToDeleteDevice {
            get {
                return ResourceManager.GetString("NoPermissionToDeleteDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app does not have the required permissions to delete the data of this device. ähnelt.
        /// </summary>
        internal static string NoPermissionToDeleteDeviceContents {
            get {
                return ResourceManager.GetString("NoPermissionToDeleteDeviceContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app does not have the required permissions to load this device. ähnelt.
        /// </summary>
        internal static string NoPermissionToLoadDevice {
            get {
                return ResourceManager.GetString("NoPermissionToLoadDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The app does not have the required permissions to save this device. ähnelt.
        /// </summary>
        internal static string NoPermissionToSaveDevice {
            get {
                return ResourceManager.GetString("NoPermissionToSaveDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The device does not support remote configuration. ähnelt.
        /// </summary>
        internal static string NoRemoteConfig {
            get {
                return ResourceManager.GetString("NoRemoteConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die You cannot edit settings as a guest ähnelt.
        /// </summary>
        internal static string NoSettingsGuest {
            get {
                return ResourceManager.GetString("NoSettingsGuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die OK ähnelt.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old password ähnelt.
        /// </summary>
        internal static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Old password not correct ähnelt.
        /// </summary>
        internal static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Only device ähnelt.
        /// </summary>
        internal static string OnlyDevice {
            get {
                return ResourceManager.GetString("OnlyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Password ähnelt.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Photos from &quot;{0}&quot; ähnelt.
        /// </summary>
        internal static string PhotosFrom_Name {
            get {
                return ResourceManager.GetString("PhotosFrom_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pictures ähnelt.
        /// </summary>
        internal static string Pictures {
            get {
                return ResourceManager.GetString("Pictures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Project on GitHub ähnelt.
        /// </summary>
        internal static string ProjectLinkTxt {
            get {
                return ResourceManager.GetString("ProjectLinkTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Redraw graphics ähnelt.
        /// </summary>
        internal static string RedrawGraphics {
            get {
                return ResourceManager.GetString("RedrawGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Refresh ähnelt.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repeat new password ähnelt.
        /// </summary>
        internal static string RepeatNewPassword {
            get {
                return ResourceManager.GetString("RepeatNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset ähnelt.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restart required ähnelt.
        /// </summary>
        internal static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die RTSP port ähnelt.
        /// </summary>
        internal static string RtspPort {
            get {
                return ResourceManager.GetString("RtspPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Saved ähnelt.
        /// </summary>
        internal static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save new user data ähnelt.
        /// </summary>
        internal static string SaveUser {
            get {
                return ResourceManager.GetString("SaveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Select a device to show tools and data. ähnelt.
        /// </summary>
        internal static string SelectDeviceToGetTools {
            get {
                return ResourceManager.GetString("SelectDeviceToGetTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Temperatur ähnelt.
        /// </summary>
        internal static string Temperatur {
            get {
                return ResourceManager.GetString("Temperatur", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Time ähnelt.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use camera ähnelt.
        /// </summary>
        internal static string UseCam {
            get {
                return ResourceManager.GetString("UseCam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username can not be empty ähnelt.
        /// </summary>
        internal static string UserEmpty {
            get {
                return ResourceManager.GetString("UserEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Username ähnelt.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Use measurements ähnelt.
        /// </summary>
        internal static string UseValues {
            get {
                return ResourceManager.GetString("UseValues", resourceCulture);
            }
        }
    }
}
